# Prometheus configuration for OpenGrok indexer and web application monitoring

global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

scrape_configs:

  - job_name: 'webapp'
    metrics_path: '/metrics/prometheus'
    static_configs:
      - targets: ['omon-opengrok:8080']

  - job_name: 'indexer'
    static_configs:
      - targets: ['omon-statsd-exporter:9102']
