{
 "title": "Indexer",
 "time": { "from": "2021-06-17T09:04:39.269Z", "to": "2021-06-17T09:12:03.884Z" },
 "panels": [
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "indexer_cpu_usage" }
   ]
  },
  {
   "title": "thread states",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "indexer_thread_states" }
   ]
  },
  {
   "title": "JVM heap",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "indexer_jvm_memory_used" },
    { "expr": "sum(indexer_jvm_memory_used)", "legendFormat": "Total" }
   ]
  }
 ]
}