{
 "title": "OpenGrok web app JVM metrics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "JVM memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_memory_used_bytes" },
    { "expr": "sum(jvm_memory_used_bytes)", "legendFormat": "Total" }
   ]
  },
  {
   "title": "JVM threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_threads_live_threads" }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_cpu_usage" }
   ]
  }
 ]
}